import { Language } from "@/components/language-switcher";

// Translation dictionary for all UI text
export const translations = {
  // Navigation
  navigation: {
    predictions: {
      en: "Predictions",
      es: "Predicciones",
    },
    pricing: {
      en: "Pricing",
      es: "Precios",
    },
    faq: {
      en: "FAQ",
      es: "Preguntas Frecuentes",
    },
    signIn: {
      en: "Sign In To Subscribe",
      es: "Iniciar Sesión para Suscribirse",
    },
  },

  // Hero Section
  hero: {
    badge: {
      en: "AI-Powered Predictions",
      es: "Predicciones con IA",
    },
    title: {
      en: "Make Smarter Sports Bets",
      es: "Haz Apuestas Deportivas Más Inteligentes",
    },
    description: {
      en: "BetSeguro uses advanced artificial intelligence and real-time data to predict the outcome of your favorite sports matches with high accuracy.",
      es: "BetSeguro utiliza inteligencia artificial avanzada y datos en tiempo real para predecir el resultado de tus partidos deportivos favoritos con alta precisión.",
    },
    getStarted: {
      en: "Get Started For Free",
      es: "Comienza Gratis",
    },
    howItWorks: {
      en: "See How It Works",
      es: "Mira Cómo Funciona",
    },
    features: {
      realTime: {
        en: "Real-time updates",
        es: "Actualizaciones en tiempo real",
      },
      aiPowered: {
        en: "AI powered",
        es: "Impulsado por IA",
      },
    },
  },

  // MLB Predictions Card
  mlbCard: {
    title: {
      en: "MLB Predictions",
      es: "Predicciones MLB",
    },
    accurate: {
      en: "99% Accurate",
      es: "99% Precisas",
    },
  },

  // Features Section
  features: {
    badge: {
      en: "Our Features",
      es: "Nuestras Características",
    },
    title: {
      en: "Why Choose BetSeguro?",
      es: "¿Por qué Elegir BetSeguro?",
    },
    subtitle: {
      en: "Our platform combines cutting-edge technology with sports expertise",
      es: "Nuestra plataforma combina tecnología de vanguardia con experiencia deportiva",
    },
    cards: {
      predictions: {
        title: {
          en: "Accurate Predictions",
          es: "Predicciones Precisas",
        },
        description: {
          en: "Our AI models analyze thousands of data points to deliver highly accurate predictions.",
          es: "Nuestros modelos de IA analizan miles de datos para ofrecer predicciones altamente precisas.",
        },
      },
      insights: {
        title: {
          en: "AI-Powered Insights",
          es: "Análisis Impulsado por IA",
        },
        description: {
          en: "Get detailed analysis and insights generated by our advanced AI system.",
          es: "Obtén análisis detallados generados por nuestro avanzado sistema de IA.",
        },
      },
      statistics: {
        title: {
          en: "Detailed Statistics",
          es: "Estadísticas Detalladas",
        },
        description: {
          en: "Access comprehensive statistics and trends to inform your betting decisions.",
          es: "Accede a estadísticas completas y tendencias para informar tus decisiones de apuestas.",
        },
      },
    },
  },

  // Live Predictions Section
  livePredictions: {
    badge: {
      en: "Live Predictions",
      es: "Predicciones en Vivo",
    },
    title: {
      en: "Today's MLB Game Predictions",
      es: "Predicciones de Juegos MLB de Hoy",
    },
    description: {
      en: "View upcoming MLB games and our AI-powered predictions for the best betting opportunities",
      es: "Mira los próximos juegos de MLB y nuestras predicciones impulsadas por IA para las mejores oportunidades de apuestas",
    },
    updatedEvery: {
      en: "Updated every 5 minutes with real-time data",
      es: "Actualizado cada 5 minutos con datos en tiempo real",
    },
  },

  // CTA Section
  cta: {
    title: {
      en: "Ready to make smarter sports bets?",
      es: "¿Listo para hacer apuestas deportivas más inteligentes?",
    },
    description: {
      en: "Sign up today and get unlimited access to all of our premium predictions and insights.",
      es: "Regístrate hoy y obtén acceso ilimitado a todas nuestras predicciones e insights premium.",
    },
    button: {
      en: "Get Started Now",
      es: "Comenzar Ahora",
    },
  },

  // Footer
  footer: {
    description: {
      en: "BetSeguro is the leading AI-powered sports prediction platform, helping you make better, data-driven betting decisions.",
      es: "BetSeguro es la plataforma líder de predicción deportiva impulsada por IA, ayudándote a tomar mejores decisiones de apuestas basadas en datos.",
    },
    sections: {
      product: {
        title: {
          en: "Product",
          es: "Producto",
        },
        links: {
          features: {
            en: "Features",
            es: "Características",
          },
          pricing: {
            en: "Pricing",
            es: "Precios",
          },
          api: {
            en: "API",
            es: "API",
          },
          integrations: {
            en: "Integrations",
            es: "Integraciones",
          },
        },
      },
      resources: {
        title: {
          en: "Resources",
          es: "Recursos",
        },
        links: {
          documentation: {
            en: "Documentation",
            es: "Documentación",
          },
          guides: {
            en: "Guides",
            es: "Guías",
          },
          blog: {
            en: "Blog",
            es: "Blog",
          },
          support: {
            en: "Support",
            es: "Soporte",
          },
        },
      },
    },
    legal: {
      rights: {
        en: "All rights reserved.",
        es: "Todos los derechos reservados.",
      },
      terms: {
        en: "Terms",
        es: "Términos",
      },
      privacy: {
        en: "Privacy",
        es: "Privacidad",
      },
      cookies: {
        en: "Cookies",
        es: "Cookies",
      },
    },
  },
};

// Helper function to get translation
export function getTranslation(key: string, language: Language): string {
  const keys = key.split(".");
  let result: any = translations;

  for (const k of keys) {
    if (result[k]) {
      result = result[k];
    } else {
      return key; // Return the key if translation is not found
    }
  }

  if (result[language]) {
    return result[language];
  }

  return key; // Return the key if language is not found
}
